# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night:
  font: native
  font_size: L

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: '中国科学院大学'
    description: '**云计算与智能信息处理实验室**（CCIP Lab，成立于2010年1月，隶属于中国科学院大学计算机科学与技术学院，拥有自由开放的学术氛围和国际前沿的研究方向。实验室主任为徐俊刚教授'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '版权所有 © {year} 云计算与智能信息处理实验室（CCIP Lab）'
    # license:
    #   enable: true
    #   allow_derivatives: true
    #   share_alike: true
    #   allow_commercial: true

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: zh

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/SivanLaai/ucas-ccip-website'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
    about_shape: circle
    # 404：如果没有与电子邮件哈希关联的图像，则不加载任何图像，而是返回 HTTP 404（未找到文件）响应
    # mp：一个简单的卡通风格的人物轮廓
    # identicon：一个几何图案（随机生成）
    # monsterid：具有不同颜色、面孔的“怪物”（随机生成）
    # wavatar：具有不同特征和背景的人脸（随机生成）
    # retro：8位色的像素人脸（随机生成）
    # robohash：具有不同颜色、面部的机器人（随机生成）
    # blank：透明的 PNG 图像（为方便演示，已为其添加了一个边框）
    type: robohash
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'baidu'
    api_key: '1V4mSproiau7AxsArSNKBWqR0ZiyMKNh'
    zoom: 16

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa
